version: "3"
services:
    alvara-frontend:
        container_name: alvara-frontend
        image: alvara-frontend:latest
        ports:
            - 4000:80
        restart: always
        environment:
            - PRODUCTION=false
            - apiUrl=http://cloudtecnologia.dynns.com:8090
            - CLI_ID=my-angular-app
            - CLI_SECRET=@321
            - cliente=Contabilidade NOME
