version: "3"
services:
    alvara-frontend:
        container_name: alvara-frontend
        image: alvara-frontend:latest
        ports:
            - 3001:80
        restart: always
        environment:
            - PRODUCTION=false
            - API_URL=http://cloudtecnologia.dynns.com:8002
            - VERSAO='v_03.11.2023'
            - CLI_ID=my-angular-app
            - CLI_SECRET=@321
